apiVersion: v2
name: balancing
home: "https://github.com/elf-io/balancing"
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: 0.0.2
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "0.0.2"
kubeVersion: ">= 1.16.0-0"
description: balancing
sources:
  - "https://github.com/elf-io/balancing"
keywords:
  - balancing
maintainers:
  - name: elf-io
    url: https://github.com/elf-io
